作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [3]:
import numpy as np

In [8]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

array_t = np.transpose(array1)

array_f = np.dot(array1,array_t)
array_f

array([[164,  70],
       [ 70,  34]])

In [12]:
#2. 運用上列array計算特徵值、特徵向量?

np.linalg.eig(array_f)
np.linalg.eigvals(array_f)

array([194.52486587,   3.47513413])

In [ ]:
#3. 運用上列array計算SVD?

In [13]:
np.linalg.svd(array_f)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([194.52486587,   3.47513413]),
 array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]))